# Data
data_type: 'hilp'
dataset_name: 'HardinLoopPlatform'
pretrained: null
task_type: 'classification'

# Output
out_dir: '../out/HardinLoopPlatform/GID'



seed: 6600

n_train: 500
n_val: 1000

# one class classification
one_class: False
# whether eliminate small part
eliminate_small_part: False

# Model architecture
model_name: 'GraphClf'

hidden_size: 16


# Bert configure
use_bert: False



# Regularization
dropout: 0.5 # 0.5
gl_dropout: 0.5 # 0.5


# Graph neural networks
bignn: False
graph_module: 'gcn'    # 'gcn'
graph_type: 'dynamic'
graph_learn: True
graph_metric_type: 'weighted_cosine' # weighted_cosine
graph_include_self: False
graph_skip_conn: 0 # GID: 0.8
graph_learn_regularization: True
smoothness_ratio: 0.1 # 0.1   # alpha
degree_ratio: 0.1 # 0.1       # beta
sparsity_ratio: 0.3 # 0.3     # gama
graph_learn_ratio: 0 # 0
input_graph_knn_size: 20 # weighted_cosine: 20
graph_learn_hidden_size: null
graph_learn_epsilon: 0.59 # weighted_cosine: 0.75
graph_learn_topk: null #
graph_learn_num_pers: 1 # weighted_cosine: 1
graph_hops: 2

# GAT only
gat_nhead: 8
gat_alpha: 0.2


# Training
optimizer: 'adam'
learning_rate: 0.01 # adam: 0.01
weight_decay: 0.0005 # adam: 0.0005
lr_patience: 2
lr_reduce_factor: 0.5 # GCN: 0.5
grad_clipping: null
grad_accumulated_steps: 1
eary_stop_metric: 'nloss' # negative loss
pretrain_epoch: 50 # 50
max_iter: 10 # 10
eps_adj: 2e-5 # 1e-3


# note: RL is not used
rl_ratio: 0  # use mixed objective if > 0; ratio of RL in the loss function
rl_ratio_power: 1  # increase rl_ratio by **= rl_ratio_power after each epoch; (0, 1]
rl_start_epoch: 1  # start RL at which epoch (later start can ensure a strong baseline)?
max_rl_ratio: 0.99
rl_reward_metric: 'acc'
rl_wmd_ratio: 0


random_seed: 1234
shuffle: True # Whether to shuffle the examples during training
max_epochs: 10000
patience: 100
verbose: 20
print_every_epochs: 500 # Print every X epochs


# Testing
out_predictions: False # Whether to output predictions
out_raw_learned_adj_path: 'HILP_GID_raw_learned_adj.npy'
save_params: True # Whether to save params
logging: True # Turn it off for Codalab


# Device
no_cuda: False
# cuda_id: -1
cuda_id: 2
